# Generated by Django 2.0.4 on 2018-05-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='산지조합명',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='수산물표준코드명',
            field=models.TextField(),
        ),
    ]
