# Generated by Django 2.0.4 on 2018-05-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0002_auto_20180529_0650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='place',
        ),
    ]
