# Generated by Django 2.0.4 on 2018-05-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myHome', '0003_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('수산물표준코드명', models.TextField()),
                ('산지조합명', models.TextField()),
            ],
        ),
    ]
